print("##############################")
print("#                            #")
print("#   Rizki Adhitiya Maulana   #")
print("#        2410817110014       #")
print("#                            #")
print("##############################")